// Checklist: https://github.com/PokemonTCG/pokemon-tcg-data/blob/master/cards/en/sv3pt5.json
export const masterSet151Cards: Array<[number, string, string]> = [
  [1, "Bulbasaur", "normal"],
  [2, "Ivysaur", "normal"],
  [3, "Venusaur ex", "holo"],
  [4, "Charmander", "normal"],
  [5, "Charmeleon", "normal"],
  [6, "Charizard ex", "holo"],
  [7, "Squirtle", "normal"],
  [8, "Wartortle", "normal"],
  [9, "Blastoise ex", "holo"],
  [10, "Caterpie", "normal"],
  [11, "Metapod", "normal"],
  [12, "Butterfree", "normal"],
  [13, "Weedle", "normal"],
  [14, "Kakuna", "normal"],
  [15, "Beedrill", "holo"],
  [16, "Pidgey", "normal"],
  [17, "Pidgeotto", "normal"],
  [18, "Pidgeot", "normal"],
  [19, "Rattata", "normal"],
  [20, "Raticate", "normal"],
  [21, "Spearow", "normal"],
  [22, "Fearow", "normal"],
  [23, "Ekans", "normal"],
  [24, "Arbok ex", "holo"],
  [25, "Pikachu", "normal"],
  [26, "Raichu", "holo"],
  [27, "Sandshrew", "normal"],
  [28, "Sandslash", "normal"],
  [29, "Nidoran \u2640", "normal"],
  [30, "Nidorina", "normal"],
  [31, "Nidoqueen", "normal"],
  [32, "Nidoran \u2642", "normal"],
  [33, "Nidorino", "normal"],
  [34, "Nidoking", "holo"],
  [35, "Clefairy", "normal"],
  [36, "Clefable", "normal"],
  [37, "Vulpix", "normal"],
  [38, "Ninetales ex", "holo"],
  [39, "Jigglypuff", "normal"],
  [40, "Wigglytuff ex", "holo"],
  [41, "Zubat", "normal"],
  [42, "Golbat", "normal"],
  [43, "Oddish", "normal"],
  [44, "Gloom", "normal"],
  [45, "Vileplume", "holo"],
  [46, "Paras", "normal"],
  [47, "Parasect", "normal"],
  [48, "Venonat", "normal"],
  [49, "Venomoth", "normal"],
  [50, "Diglett", "normal"],
  [51, "Dugtrio", "normal"],
  [52, "Meowth", "normal"],
  [53, "Persian", "normal"],
  [54, "Psyduck", "normal"],
  [55, "Golduck", "normal"],
  [56, "Mankey", "normal"],
  [57, "Primeape", "normal"],
  [58, "Growlithe", "normal"],
  [59, "Arcanine", "normal"],
  [60, "Poliwag", "normal"],
  [61, "Poliwhirl", "normal"],
  [62, "Poliwrath", "normal"],
  [63, "Abra", "normal"],
  [64, "Kadabra", "normal"],
  [65, "Alakazam ex", "holo"],
  [66, "Machop", "normal"],
  [67, "Machoke", "normal"],
  [68, "Machamp", "holo"],
  [69, "Bellsprout", "normal"],
  [70, "Weepinbell", "normal"],
  [71, "Victreebel", "normal"],
  [72, "Tentacool", "normal"],
  [73, "Tentacruel", "normal"],
  [74, "Geodude", "normal"],
  [75, "Graveler", "normal"],
  [76, "Golem ex", "holo"],
  [77, "Ponyta", "normal"],
  [78, "Rapidash", "normal"],
  [79, "Slowpoke", "normal"],
  [80, "Slowbro", "normal"],
  [81, "Magnemite", "normal"],
  [82, "Magneton", "normal"],
  [83, "Farfetch'd", "normal"],
  [84, "Doduo", "normal"],
  [85, "Dodrio", "holo"],
  [86, "Seel", "normal"],
  [87, "Dewgong", "normal"],
  [88, "Grimer", "normal"],
  [89, "Muk", "normal"],
  [90, "Shellder", "normal"],
  [91, "Cloyster", "normal"],
  [92, "Gastly", "normal"],
  [93, "Haunter", "normal"],
  [94, "Gengar", "holo"],
  [95, "Onix", "normal"],
  [96, "Drowzee", "normal"],
  [97, "Hypno", "normal"],
  [98, "Krabby", "normal"],
  [99, "Kingler", "normal"],
  [100, "Voltorb", "normal"],
  [101, "Electrode", "holo"],
  [102, "Exeggcute", "normal"],
  [103, "Exeggutor", "normal"],
  [104, "Cubone", "normal"],
  [105, "Marowak", "holo"],
  [106, "Hitmonlee", "normal"],
  [107, "Hitmonchan", "normal"],
  [108, "Lickitung", "normal"],
  [109, "Koffing", "normal"],
  [110, "Weezing", "holo"],
  [111, "Rhyhorn", "normal"],
  [112, "Rhydon", "normal"],
  [113, "Chansey", "holo"],
  [114, "Tangela", "normal"],
  [115, "Kangaskhan ex", "holo"],
  [116, "Horsea", "normal"],
  [117, "Seadra", "normal"],
  [118, "Goldeen", "normal"],
  [119, "Seaking", "normal"],
  [120, "Staryu", "normal"],
  [121, "Starmie", "holo"],
  [122, "Mr. Mime", "holo"],
  [123, "Scyther", "normal"],
  [124, "Jynx ex", "holo"],
  [125, "Electabuzz", "normal"],
  [126, "Magmar", "normal"],
  [127, "Pinsir", "normal"],
  [128, "Tauros", "normal"],
  [129, "Magikarp", "normal"],
  [130, "Gyarados", "holo"],
  [131, "Lapras", "normal"],
  [132, "Ditto", "holo"],
  [133, "Eevee", "normal"],
  [134, "Vaporeon", "holo"],
  [135, "Jolteon", "holo"],
  [136, "Flareon", "holo"],
  [137, "Porygon", "normal"],
  [138, "Omanyte", "normal"],
  [139, "Omastar", "holo"],
  [140, "Kabuto", "normal"],
  [141, "Kabutops", "holo"],
  [142, "Aerodactyl", "holo"],
  [143, "Snorlax", "normal"],
  [144, "Articuno", "holo"],
  [145, "Zapdos ex", "holo"],
  [146, "Moltres", "holo"],
  [147, "Dratini", "normal"],
  [148, "Dragonair", "normal"],
  [149, "Dragonite", "holo"],
  [150, "Mewtwo", "holo"],
  [151, "Mew ex", "holo"],
  [152, "Antique Dome Fossil", "normal"],
  [153, "Antique Helix Fossil", "normal"],
  [154, "Antique Old Amber", "normal"],
  [155, "Big Air Balloon", "normal"],
  [156, "Bill's Transfer", "normal"],
  [157, "Cycling Road", "normal"],
  [158, "Daisy's Help", "normal"],
  [159, "Energy Sticker", "normal"],
  [160, "Erika's Invitation", "normal"],
  [161, "Giovanni's Charisma", "normal"],
  [162, "Grabber", "normal"],
  [163, "Leftovers", "normal"],
  [164, "Protective Goggles", "normal"],
  [165, "Rigid Band", "normal"],
  [166, "Bulbasaur", "normal"],
  [167, "Ivysaur", "normal"],
  [168, "Charmander", "normal"],
  [169, "Charmeleon", "normal"],
  [170, "Squirtle", "normal"],
  [171, "Wartortle", "normal"],
  [172, "Caterpie", "normal"],
  [173, "Pikachu", "normal"],
  [174, "Nidoking", "normal"],
  [175, "Psyduck", "normal"],
  [176, "Poliwhirl", "normal"],
  [177, "Machoke", "normal"],
  [178, "Tangela", "normal"],
  [179, "Mr. Mime", "normal"],
  [180, "Omanyte", "normal"],
  [181, "Dragonair", "normal"],
  [182, "Venusaur ex", "normal"],
  [183, "Charizard ex", "normal"],
  [184, "Blastoise ex", "normal"],
  [185, "Arbok ex", "normal"],
  [186, "Ninetales ex", "normal"],
  [187, "Wigglytuff ex", "normal"],
  [188, "Alakazam ex", "normal"],
  [189, "Golem ex", "normal"],
  [190, "Kangaskhan ex", "normal"],
  [191, "Jynx ex", "normal"],
  [192, "Zapdos ex", "normal"],
  [193, "Mew ex", "normal"],
  [194, "Bill's Transfer", "normal"],
  [195, "Daisy's Help", "normal"],
  [196, "Erika's Invitation", "normal"],
  [197, "Giovanni's Charisma", "normal"],
  [198, "Venusaur ex", "normal"],
  [199, "Charizard ex", "normal"],
  [200, "Blastoise ex", "normal"],
  [201, "Alakazam ex", "normal"],
  [202, "Zapdos ex", "normal"],
  [203, "Erika's Invitation", "normal"],
  [204, "Giovanni's Charisma", "normal"],
  [205, "Mew ex", "normal"],
  [206, "Switch", "normal"],
  [207, "Basic Psychic Energy", "normal"],
];

export function masterSet151Contents() {
  const expansion = "Scarlet & Violet 151";
  const entries = masterSet151Cards.flatMap(([number, name, finish]) => {
    const base = { entryKey: `151:${number}:base`, name, expansion, number: String(number), finish };
    return number <= 165 && !name.endsWith(" ex")
      ? [base, { ...base, entryKey: `151:${number}:reverse`, finish: "reverse holo" }]
      : [base];
  });
  return [...entries, ...["Grass", "Fire", "Water", "Lightning", "Psychic", "Fighting", "Darkness", "Metal"].map((type) => ({
    entryKey: `151:energy:${type.toLowerCase()}`, name: `${type} Energy`, expansion, number: "", finish: "cosmos holo"
  }))];
}
