import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {it,type TestContext} from 'node:test';
import {createOperationalDatabase,registerTournamentAccount,loginTournamentAccount,getTournamentAccount,logoutTournamentAccount,getAuthenticatedUserContext,createSpaceTournament,getSpaceTournament,listSpaceTournaments,commandSpaceTournament} from './index.js';
async function fixture(t:TestContext){const dir=await mkdtemp(path.join(tmpdir(),'ultimoturno-space-'));const db=await createOperationalDatabase({dataDir:dir});t.after(async()=>{await db.close();await rm(dir,{recursive:true,force:true});});return db;}
it('public accounts own independent sessions and tournaments without creating Stock users or roles',async t=>{
  const db=await fixture(t);
  const before=await db.query<{count:string}>('select count(*)::text as count from app_users');
  const a=await registerTournamentAccount(db,{displayName:'Ana',email:'Ana@test.local',password:'secure-test-123'},'127.0.0.1');
  const b=await registerTournamentAccount(db,{displayName:'Bruno',email:'bruno@test.local',password:'secure-test-456'},'127.0.0.2');
  assert.equal(a.account.email,'ana@test.local');assert.equal((await getTournamentAccount(db,a.token))?.id,a.account.id);
  assert.equal(await getAuthenticatedUserContext(db,a.token),null);
  const hash=await db.query<{password_hash:string}>('select password_hash from tournament_accounts where id=$1',[a.account.id]);
  assert.ok(!hash.rows[0].password_hash.includes('secure-test'));
  const sessions=await db.query<{token_hash:string}>('select token_hash from tournament_sessions where account_id=$1',[a.account.id]);
  assert.ok(sessions.rows.every(r=>r.token_hash!==a.token));
  const input={id:crypto.randomUUID(),name:'Copa privada',swissCount:3,cutSize:0};
  const created=await createSpaceTournament(db,input,a.account);
  assert.deepEqual(await createSpaceTournament(db,input,a.account),created);
  assert.equal((await listSpaceTournaments(db,a.account)).length,1);
  assert.deepEqual(await listSpaceTournaments(db,b.account),[]);
  await assert.rejects(()=>getSpaceTournament(db,input.id,b.account),/no encontrado/);
  await assert.rejects(()=>commandSpaceTournament(db,input.id,{version:1,command:{type:'addPlayer',name:'Ajeno',playerId:''}},b.account),/no encontrado/);
  const changed=await commandSpaceTournament(db,input.id,{version:1,command:{type:'addPlayer',name:'Eva',playerId:''}},a.account);
  assert.equal(changed.version,2);
  await assert.rejects(()=>commandSpaceTournament(db,input.id,{version:1,command:{type:'addPlayer',name:'Otro',playerId:''}},a.account),/Otro equipo/);
  const login=await loginTournamentAccount(db,{email:'ANA@test.local',password:'secure-test-123'},'127.0.0.1');
  const same=await getTournamentAccount(db,login.token);assert.equal(same?.id,a.account.id);
  assert.equal((await getSpaceTournament(db,input.id,same!)).state.players.length,1);
  await logoutTournamentAccount(db,a.token);assert.equal(await getTournamentAccount(db,a.token),null);
  assert.ok(await getTournamentAccount(db,login.token));
  await db.query("update tournament_sessions set expires_at=now()-interval '1 hour' where account_id=$1",[a.account.id]);
  assert.equal(await getTournamentAccount(db,login.token),null);
  const after=await db.query<{count:string}>('select count(*)::text as count from app_users');assert.equal(after.rows[0].count,before.rows[0].count);
  assert.equal((await db.query('select id from tournaments')).rows.length,0);
});
it('rejects invalid credentials and passwords, duplicate accounts and throttles failed logins',async t=>{
  const db=await fixture(t);
  await assert.rejects(()=>registerTournamentAccount(db,{displayName:'A',email:'not-email',password:'secure-test-123'}));
  await assert.rejects(()=>registerTournamentAccount(db,{displayName:'A',email:'a@test.local',password:'short'}));
  await registerTournamentAccount(db,{displayName:'A',email:'a@test.local',password:'secure-test-123'});
  await assert.rejects(()=>registerTournamentAccount(db,{displayName:'A',email:'A@test.local',password:'secure-test-123'}),/Ya existe/);
  for(let i=0;i<10;i++)await assert.rejects(()=>loginTournamentAccount(db,{email:'a@test.local',password:'wrong'},'192.0.2.1'),/incorrectos/);
  await assert.rejects(()=>loginTournamentAccount(db,{email:'a@test.local',password:'secure-test-123'},'192.0.2.1'),(e:unknown)=>(e as {statusCode?:number}).statusCode===429);
  assert.equal((await db.query('select * from tournament_auth_attempts where action=\'login\'')).rows.length,10);
  assert.equal((await db.query('select * from tournament_accounts')).rows.length,1);
});
