import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { it } from 'node:test';
import { createOperationalDatabase, getDefaultOperationalUser, createTournament, getTournament, listTournaments, commandTournament } from './index.js';
it('tournaments persist across sessions, reject stale writes, protect businesses and do not touch stock',async context=>{
  const dir=await mkdtemp(path.join(tmpdir(),'ultimoturno-tournament-'));
  const db=await createOperationalDatabase({dataDir:dir});
  context.after(async()=>{await db.close();await rm(dir,{recursive:true,force:true});});
  const admin={...await getDefaultOperationalUser(db),roles:['admin']};
  const id=crypto.randomUUID();const input={id,name:'Copa local',swissCount:3,cutSize:4};
  const created=await createTournament(db,input,admin);
  assert.equal(created.version,1);
  const replay=await createTournament(db,input,admin);assert.deepEqual(replay,created);
  await assert.rejects(()=>createTournament(db,{...input,name:'Otro'},admin),/otro torneo/);
  const fromOtherPc=await getTournament(db,id,{...admin});assert.deepEqual(fromOtherPc,created);
  const changed=await commandTournament(db,id,{version:1,command:{type:'addPlayer',name:'Ana',playerId:'1'}},admin);
  assert.equal(changed.version,2);assert.equal(changed.state.players.length,1);
  await assert.rejects(()=>commandTournament(db,id,{version:1,command:{type:'addPlayer',name:'Bruno',playerId:'2'}},admin),/Otro equipo/);
  assert.equal((await getTournament(db,id,admin)).state.players.length,1);
  await assert.rejects(()=>commandTournament(db,id,{version:2,command:{type:'nextSwiss'}},admin),/dos jugadores/);
  assert.equal((await getTournament(db,id,admin)).version,2);
  const secondBusiness={...admin,businessId:crypto.randomUUID()};
  await assert.rejects(()=>getTournament(db,id,secondBusiness),/no encontrado/);
  assert.deepEqual(await listTournaments(db,secondBusiness),[]);
  await assert.rejects(()=>listTournaments(db,{...admin,roles:['reseller']}),/administrador/);
  await assert.rejects(()=>commandTournament(db,id,{version:2,command:{type:'nextSwiss'}},{...admin,roles:['stock_owner']}),/administrador/);
  await assert.rejects(()=>createTournament(db,{...input,id:crypto.randomUUID(),imported:{name:'Bad'}},admin));
  assert.equal((await listTournaments(db,admin)).length,1);
  const before=await db.query<{count:string}>('select count(*)::text as count from inventory_items');
  assert.equal(before.rows[0].count,'0');
});
